"""create leagues teams players table

Revision ID: 50399dc5293b
Revises: ffdc0a98111c
Create Date: 2022-08-13 18:05:08.484177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50399dc5293b'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(length=40), nullable=False),
    sa.Column('league_image', sa.String(length=500), nullable=True),
    sa.Column('league_note_title', sa.String(length=40), nullable=True),
    sa.Column('league_note', sa.String(length=1000), nullable=True),
    sa.Column('team_limit', sa.Integer(), nullable=False),
    sa.Column('team_player_limit', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=11), nullable=True),
    sa.Column('start_time', sa.String(length=11), nullable=True),
    sa.Column('start_standard', sa.DateTime(), nullable=True),
    sa.Column('field_goal_made_weight', sa.Integer(), nullable=True),
    sa.Column('field_goal_attempted_weight', sa.Integer(), nullable=True),
    sa.Column('free_throw_made_weight', sa.Integer(), nullable=True),
    sa.Column('free_throw_attempted_weight', sa.Integer(), nullable=True),
    sa.Column('three_point_made_weight', sa.Integer(), nullable=True),
    sa.Column('assists_weight', sa.Integer(), nullable=True),
    sa.Column('rebounds_weight', sa.Integer(), nullable=True),
    sa.Column('steals_weight', sa.Integer(), nullable=True),
    sa.Column('blocks_weight', sa.Integer(), nullable=True),
    sa.Column('turnovers_weight', sa.Integer(), nullable=True),
    sa.Column('points_weight', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=40), nullable=False),
    sa.Column('player_image', sa.String(length=500), nullable=True),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('team', sa.String(length=40), nullable=True),
    sa.Column('bio', sa.String(length=1000), nullable=True),
    sa.Column('recent_news', sa.String(length=1000), nullable=True),
    sa.Column('field_goal_made', sa.Integer(), nullable=True),
    sa.Column('field_goal_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throw_made', sa.Integer(), nullable=True),
    sa.Column('free_throw_attempted', sa.Integer(), nullable=True),
    sa.Column('three_point_made', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('fantasy_total', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_owner_id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(length=30), nullable=False),
    sa.Column('team_abre', sa.String(length=4), nullable=False),
    sa.Column('team_image', sa.String(length=500), nullable=True),
    sa.Column('fantasy_total', sa.Integer(), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_teams',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('team_id', 'player_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_teams')
    op.drop_table('teams')
    op.drop_table('players')
    op.drop_table('leagues')
    # ### end Alembic commands ###
